### ISSUE TITLE
Content cut off in PDF

### ISSUE THREAD

**Issue by n-d-r-d-g** [n-d-r-d-g/devcon-scheduler#10]
### Currently

On some mobile devices, when exporting a PDF via the `Save` button, the content gets cut off if it reaches the end of the page and there is not enough space to fit the whole session card on the current page.

### Expected

You can use the following in globals to fix this:
```css
.a4-page {
  @apply bg-white;

  min-inline-size: 210mm;
  inline-size: 210mm;
  max-inline-size: 100%;
  min-block-size: 297mm;
  padding: 25.4mm;

  @media print {
    padding: 0;
  }
}
```

You will need to add the `a4-page` class to the root element in the `PDFPreview` component for it to work.
